### ISSUE TITLE
Builds failing due to this: ERROR: 1 error occurred:  You must first sign the relevant contracts online.

### ISSUE THREAD

**Issue by garyo** [jimeh/emacs-builds#26]
Recent builds are failing to package due to the dev (@jimeh ) needing to log in to Apple and re-sign the relevant dev contracts I believe. Thank you for doing these builds by the way!!!

**Comment by jimeh** [comment]
@garyo thanks for bringing that to my attention :)

My free time should be returning to normal levels again tail end of this month, at which point I'll be paying some much needed attention to a few outstanding issues here and get them resolved.

**Comment by jimeh** [comment]
P.S. 🤦‍♂️ I forgot to mention, I've accepted Apple's new terms, so builds should start passing again. I'll leave it open for now and see how tonight's nightly builds go.

The completed builds may still be affected by #25 though, as I've not had time to get a fix fully working yet.

**Comment by jimeh** [comment]
We got a new set of builds last night, so I believe this is safe to close now :)
