### ISSUE TITLE
Where is the emacs-module.h path?

### ISSUE THREAD

**Issue by yibie** [jimeh/emacs-builds#31]
I'm type 'where emacs', and 'which emacs' in  terminal, but they give me the wrong answer.

**Comment by jimeh** [comment]
Do you mind elaborating a bit more? How did you install via Homebrew, or manually download the dmg and drag the app to your Applications folder?

**Comment by shipmints** [comment]
I assume you found the file by now? What does
```
ls -l /Applications/Emacs.app/Contents/Resources/include/emacs-module.h
```
produce for you?

If you are developing a module, I recommend reading this https://phst.eu/emacs-modules.html

**Comment by yibie** [comment]
I was finally found that the Emacs is con
