### ISSUE TITLE
FR: provide emacs-30.0.9x build, pls

### ISSUE THREAD

**Issue by paaguti** [jimeh/emacs-builds#32]
I'm testing on the emacs-30 branch on Linux and would like to be able to test the emacs-30 on macOS with native compilation. I'm compiling Emacs for macOS on my system but without it.

Thanks!

**Comment by somallg** [comment]
Per this [PR](https://github.com/jimeh/homebrew-emacs-builds/commit/eb7deedd627c00a698dc809e2120148b6c6632d1)
emacs-app-pretest point to 30.0.91-pretest
So you simply need to

`brew install --case emacs-app-pretest`

**Comment by paaguti** [comment]
Too busy to react... Thanks a ton!
