### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by shipmints** [jimeh/emacs-builds#33]
I've just switched to your 29.4 build away from https://emacsformacosx.com/ and it's like day and night. https://www.reddit.com/r/emacs/comments/1ft2lnt/psa_night_and_day_mac_emacs_builds_caldwell_night/

Thank you very much.

**Comment by shipmints** [comment]
Another potentially useful nix Emacs builder https://github.com/purcell/nix-emacs-ci in addition to https://github.com/caldwell/build-emacs

**Comment by jimeh** [comment]
Thanks for the kind words both of you :)

Hopefully no hard feelings if I close this issue though, as I'm tidying up the issue list a bit... lol
