### ISSUE TITLE
Patches submitted for upstream inclusion?

### ISSUE THREAD

**Issue by shipmints** [jimeh/emacs-builds#36]
It's too bad that Emacs 30 is now pretty much locked down except for bug fixes. There is still time to get the patches on which emacs-build depends from @d12frosted submitted for upstream inclusion in Emacs 31. Does anyone know the status of each patch and if each has already been submitted and its status (rejected, awaiting feedback, awaiting review, etc.)?

**Comment by jimeh** [comment]
I'm afraid I don't know that much about the source and/or status of patches that emacs-plus maintains, despite the fact that I shamelessly borrow them for my builds here.

This is probably a question that's better to ask on the [emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus/issues) repository.

**Comment by shipmints** [comment]
See https://github.com/d12frosted/homebrew-emacs-plus/discussions/763
